---
# Source: architecture-angular/templates/credentials.yaml
apiVersion: v1
kind: Secret
metadata:
  name: gitops-react-app-docker-credentials
  labels:
    app.kubernetes.io/name: gitops-react-app
    app.kubernetes.io/instance: gitops-react-app
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: your-pat-token
